//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Order_id { get; set; }
        public System.DateTime Check_in_date { get; set; }
        public string Check_out_date { get; set; }
        public string Price { get; set; }
        public int CustomerCustomer_id { get; set; }
        public float RoomRoom_number { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Room Room { get; set; }
    }
}
